/****************************************
 * NOMBRE: Adrián Sanz Contreras        *
 * DNI: 49097240-Z                      *
 * Nº EXP: 145                          *
 *                                      *
 * NOMBRE: Alfonso Santamaría Rodríguez *
 * DNI: 49095131-K                      *   
 * Nº EXP: 63                           *
 *                                      *
 * NOMBRE: Fco Javier Pasamontes Moreno *
 * DNI: 47516684-H                      *
 * Nº EXP: 153                          *
 *                                      *
 * 2º GRADO EN INGERNIERÍA DEL SOFTWARE *
 * CURSO: 2011-2012                     *
 ****************************************/


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AccesoAProveedoresIG.java
 *
 * Created on 10-dic-2011, 6:10:11
 */
package practicaGrupal;
import java.util.ArrayList;


public class AccesoAProveedoresIG extends javax.swing.JDialog {

    private ArrayList<Proveedor> misProveedores = new ArrayList<Proveedor>();
    private ArrayList<CocheConcesionario> cochesConcesionario =
            new ArrayList<CocheConcesionario>();
    
    /** Creates new form AccesoAProveedoresIG */
    public AccesoAProveedoresIG(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbGestionProveedores = new javax.swing.JButton();
        jbGestionListasCoches = new javax.swing.JButton();
        jbComprarCocheProveedor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Acceso a proveedores");

        jbGestionProveedores.setText("Gestión de proveedores");
        jbGestionProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbGestionProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGestionProveedoresActionPerformed(evt);
            }
        });

        jbGestionListasCoches.setText("Gestión de listas de coches de cada proveedor");
        jbGestionListasCoches.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbGestionListasCoches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGestionListasCochesActionPerformed(evt);
            }
        });

        jbComprarCocheProveedor.setText("Comprar un coche a un determinado proveedor");
        jbComprarCocheProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbComprarCocheProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbComprarCocheProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jbGestionListasCoches, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbGestionProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbComprarCocheProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbComprarCocheProveedor, jbGestionListasCoches, jbGestionProveedores});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jbGestionProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbGestionListasCoches, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbComprarCocheProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbComprarCocheProveedor, jbGestionListasCoches, jbGestionProveedores});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbGestionProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGestionProveedoresActionPerformed
      GestionDeProveedoresIG gesProv = new GestionDeProveedoresIG(null,true);
      
      gesProv.setMisProveedores(this.misProveedores);
      gesProv.cargarProveedores(this.misProveedores); 
      
      gesProv.setLocationRelativeTo(null);
      gesProv.setVisible(true);
      
      this.misProveedores = gesProv.getMisProveedores();
    }//GEN-LAST:event_jbGestionProveedoresActionPerformed

    private void jbGestionListasCochesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGestionListasCochesActionPerformed
      GestionDeCochesDeProveedoresIG gesProv = new GestionDeCochesDeProveedoresIG(null,true);
      
      gesProv.setMisProveedores(this.misProveedores);
      gesProv.cargarProveedores();
            
      gesProv.setLocationRelativeTo(null);
      gesProv.setVisible(true);
      
      this.misProveedores = gesProv.getMisProveedores();
    }//GEN-LAST:event_jbGestionListasCochesActionPerformed

    private void jbComprarCocheProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbComprarCocheProveedorActionPerformed
        ComprarCocheAProveedorIG compCar = new ComprarCocheAProveedorIG(null,true);
        
        compCar.setMisProveedores(this.misProveedores);
        compCar.setMisCochesConcesionario(this.cochesConcesionario);
        compCar.cargarProveedores();
       
        compCar.setLocationRelativeTo(null);
        compCar.setVisible(true);
        
        this.misProveedores = compCar.getMisProveedores();
        this.cochesConcesionario = compCar.getMisCochesConcesionario();
        
    }//GEN-LAST:event_jbComprarCocheProveedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccesoAProveedoresIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccesoAProveedoresIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccesoAProveedoresIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccesoAProveedoresIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                AccesoAProveedoresIG dialog = new AccesoAProveedoresIG(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbComprarCocheProveedor;
    private javax.swing.JButton jbGestionListasCoches;
    private javax.swing.JButton jbGestionProveedores;
    // End of variables declaration//GEN-END:variables

    public ArrayList<CocheConcesionario> getCochesConcesionario() {
        return cochesConcesionario;
    }

    public void setCochesConcesionario(ArrayList<CocheConcesionario> cochesConcesionario) {
        this.cochesConcesionario = cochesConcesionario;
    }

    public ArrayList<Proveedor> getMisProveedores() {
        return misProveedores;
    }

    public void setMisProveedores(ArrayList<Proveedor> misProveedores) {
        this.misProveedores = misProveedores;
    }
}
