/****************************************
 * NOMBRE: Adrián Sanz Contreras        *
 * DNI: 49097240-Z                      *
 * Nº EXP: 145                          *
 *                                      *
 * NOMBRE: Alfonso Santamaría Rodríguez *
 * DNI: 49095131-K                      *   
 * Nº EXP: 63                           *
 *                                      *
 * NOMBRE: Fco Javier Pasamontes Moreno *
 * DNI: 47516684-H                      *
 * Nº EXP: 153                          *
 *                                      *
 * 2º GRADO EN INGERNIERÍA DEL SOFTWARE *
 * CURSO: 2011-2012                     *
 ****************************************/

/*
 * ConsultaCochesVendidosComisionarioIG.java
 *
 * Created on 13-dic-2011, 20:27:08
 */
package practicaGrupal;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


public class ConsultaCochesVendidosComisionarioIG extends javax.swing.JDialog {

    private ArrayList<Comisionario> listaComisionario;

    /** Creates new form ConsultaCochesVendidosComisionarioIG */
    public ConsultaCochesVendidosComisionarioIG(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public ArrayList<Comisionario> getListaComisionario() {
        return listaComisionario;
    }

    public void setListaComisionario(ArrayList<Comisionario> listaComisionario) {
        this.listaComisionario = listaComisionario;
    }

    public void CargarComisionario(ArrayList<Comisionario> misComisionarios) {
        DefaultTableModel modelo = new DefaultTableModel();
        jtCoches.setModel(new DefaultTableModel());
        modelo.addColumn("Nombre");
        modelo.addColumn("DNI");

        Object[] fila = new Object[2];
        int i;
        for (i = 0; i < misComisionarios.size(); i++) {
            fila[0] = misComisionarios.get(i).getNombre();
            fila[1] = misComisionarios.get(i).getDni();
            modelo.addRow(fila);
        }
        jtComisionario.setModel(modelo);
        this.setListaComisionario(misComisionarios);
    }

    public void CargarCoches(Comisionario Comi) {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Marca");
        modelo.addColumn("Modelo");
        modelo.addColumn("Matricula");
        modelo.addColumn("Tipo Vehiculo");

        Object[] fila = new Object[4];
        for (int i = 0; i < Comi.getCoches().size(); i++) {
            fila[0] = Comi.getCoches().get(i).getMarca();
            fila[1] = Comi.getCoches().get(i).getModelo();
            fila[2] = Comi.getCoches().get(i).getMatricula();
            fila[3] = Comi.getCoches().get(i).getTipoVehiculo();
            modelo.addRow(fila);
        }
        jtCoches.setModel(modelo);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtComisionario = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtCoches = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Coches vendidos por un comisionario");

        jtComisionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtComisionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtComisionarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtComisionario);

        jtCoches.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtCoches);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabel1)
                .addContainerGap(253, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(149, 149, 149))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jtComisionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtComisionarioMouseClicked
    // TODO add your handling code here:
    int i = 0;
    while ((!jtComisionario.isRowSelected(i)) && (i < jtComisionario.getRowCount())) {
        i++;
    }
    if (jtComisionario.isRowSelected(i)) {
        this.CargarCoches(this.listaComisionario.get(i));
        jLabel1.setText("Sueldo: " + String.valueOf(this.listaComisionario.get(i).getCoches().size() * 200) + " €");
    }
}//GEN-LAST:event_jtComisionarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaCochesVendidosComisionarioIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaCochesVendidosComisionarioIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaCochesVendidosComisionarioIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaCochesVendidosComisionarioIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ConsultaCochesVendidosComisionarioIG dialog = new ConsultaCochesVendidosComisionarioIG(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtCoches;
    private javax.swing.JTable jtComisionario;
    // End of variables declaration//GEN-END:variables
}
