/****************************************
 * NOMBRE: Adrián Sanz Contreras        *
 * DNI: 49097240-Z                      *
 * Nº EXP: 145                          *
 *                                      *
 * NOMBRE: Alfonso Santamaría Rodríguez *
 * DNI: 49095131-K                      *   
 * Nº EXP: 63                           *
 *                                      *
 * NOMBRE: Fco Javier Pasamontes Moreno *
 * DNI: 47516684-H                      *
 * Nº EXP: 153                          *
 *                                      *
 * 2º GRADO EN INGERNIERÍA DEL SOFTWARE *
 * CURSO: 2011-2012                     *
 ****************************************/

/*
 * GestionarCochesConcesionarioIG.java
 *
 * Created on 13-dic-2011, 14:58:56
 */
package practicaGrupal;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class GestionarCochesConcesionarioIG extends javax.swing.JDialog {

    private ArrayList<CocheConcesionario> misCochesC =
            new ArrayList<CocheConcesionario>();
    private int[] posRealCoche;
    private int rowCocheSeleccionado = 0;

    /** Creates new form GestionarCochesConcesionarioIG */
    public GestionarCochesConcesionarioIG(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbModificarDatos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtCochesConcesionario = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestionar los coches del concesionario");

        jbModificarDatos.setText("Modificar datos");
        jbModificarDatos.setEnabled(false);
        jbModificarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarDatosActionPerformed(evt);
            }
        });

        jtCochesConcesionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtCochesConcesionarioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtCochesConcesionario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jbModificarDatos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbModificarDatos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtCochesConcesionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtCochesConcesionarioMouseClicked
        this.rowCocheSeleccionado = this.jtCochesConcesionario.rowAtPoint(evt.getPoint());

        if (this.rowCocheSeleccionado >= 0 && this.jtCochesConcesionario.isEnabled()) {
            this.jbModificarDatos.setEnabled(true);
        }
    }//GEN-LAST:event_jtCochesConcesionarioMouseClicked

    private void jbModificarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarDatosActionPerformed
        ModificarCocheConcesionarioIG mcc = new ModificarCocheConcesionarioIG(null, true);

        this.posRealCoche = this.posicionRealCoche(misCochesC);
        mcc.setMisCochesC(this.misCochesC);
        mcc.setRowCocheSeleccionado(this.posRealCoche[this.rowCocheSeleccionado]);
        mcc.cargarDatos();

        mcc.setLocationRelativeTo(null);
        mcc.setVisible(true);

        this.setMisCochesC(mcc.getMisCochesC());
        this.cargarCochesDeConcesionario();
    }//GEN-LAST:event_jbModificarDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarCochesConcesionarioIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarCochesConcesionarioIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarCochesConcesionarioIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarCochesConcesionarioIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                GestionarCochesConcesionarioIG dialog = new GestionarCochesConcesionarioIG(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbModificarDatos;
    private javax.swing.JTable jtCochesConcesionario;
    // End of variables declaration//GEN-END:variables

    public ArrayList<CocheConcesionario> getMisCochesC() {
        return misCochesC;
    }

    public void setMisCochesC(ArrayList<CocheConcesionario> misCochesC) {
        this.misCochesC = misCochesC;
    }

    public int getRowCocheSeleccionado() {
        return rowCocheSeleccionado;
    }

    public void setRowCocheSeleccionado(int rowCocheSeleccionado) {
        this.rowCocheSeleccionado = rowCocheSeleccionado;
    }

    public void cargarCochesDeConcesionario() {
        DefaultTableModel modeloCoches = new DefaultTableModel();

        modeloCoches.addColumn("Marca");
        modeloCoches.addColumn("Modelo");
        modeloCoches.addColumn("Precio venta");
        modeloCoches.addColumn("Matrícula");
        modeloCoches.addColumn("Tipo de vehículo");

        //Recorremos los coches del concesionario y añadimos fila
        Object[] filaCoches = new Object[5];
        for (int i = 0; i < this.misCochesC.size(); i++) {
            if ((misCochesC.get(i).getEstado().equalsIgnoreCase("En venta"))
                    || (misCochesC.get(i).getEstado().equalsIgnoreCase("Reparacion"))) {
                filaCoches[0] = this.misCochesC.get(i).getMarca();
                filaCoches[1] = this.misCochesC.get(i).getModelo();
                filaCoches[2] = this.misCochesC.get(i).getPrecioVenta();
                filaCoches[3] = this.misCochesC.get(i).getMatricula();
                filaCoches[4] = this.misCochesC.get(i).getTipoVehiculo();

                modeloCoches.addRow(filaCoches);
            }
        }
        this.jbModificarDatos.setEnabled(false);

        this.jtCochesConcesionario.setModel(modeloCoches);
    }

    public int[] posicionRealCoche(ArrayList<CocheConcesionario> listaCoche) {
        int[] posRealCoche = new int[listaCoche.size()];
        int j = 0;
        for (int i = 0; i < listaCoche.size(); i++) {
            if ((listaCoche.get(i).getEstado().equalsIgnoreCase("En venta"))
                    || (listaCoche.get(i).getEstado().equalsIgnoreCase("Reparacion"))) {
                posRealCoche[j] = i;
                j++;
            }
        }
        return posRealCoche;
    }
}
