/****************************************
 * NOMBRE: Adrián Sanz Contreras        *
 * DNI: 49097240-Z                      *
 * Nº EXP: 145                          *
 *                                      *
 * NOMBRE: Alfonso Santamaría Rodríguez *
 * DNI: 49095131-K                      *   
 * Nº EXP: 63                           *
 *                                      *
 * NOMBRE: Fco Javier Pasamontes Moreno *
 * DNI: 47516684-H                      *
 * Nº EXP: 153                          *
 *                                      *
 * 2º GRADO EN INGERNIERÍA DEL SOFTWARE *
 * CURSO: 2011-2012                     *
 ****************************************/
/*
 * ReparacionIG.java
 *
 * Created on 10-dic-2011, 17:00:24
 */
package practicaGrupal;

import javax.swing.DefaultComboBoxModel;
import java.util.GregorianCalendar;


public class ReparacionIG extends javax.swing.JDialog {

    private Reparacion rep;
    private CocheConcesionario cocheC;

    /** Creates new form ReparacionIG */
    public ReparacionIG(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public DefaultComboBoxModel ModeloComboBox(int max) {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 1; i <= max; i++) {
            modelo.addElement(i);
        }
        return modelo;
    }

    public CocheConcesionario getCocheC() {
        return cocheC;
    }

    public void setCocheC(CocheConcesionario cocheC) {
        this.cocheC = cocheC;
    }

    public void inicializarIG() {
        DefaultComboBoxModel mAnios = new DefaultComboBoxModel();
        GregorianCalendar fecha = new GregorianCalendar();
        for (int i = fecha.getTime().getYear() + 1900; i != 1969; i--) {
            mAnios.addElement(i);
        }
        jComboBox3.setModel(mAnios);

        this.DarFormato();
        jComboBox2.setSelectedIndex(fecha.getTime().getMonth());
        jComboBox1.setSelectedIndex(fecha.getTime().getDate() - 1);
    }

    public void DarFormato() {
        int i = 0;
        int d = 0;
        d = jComboBox1.getSelectedIndex();
        DefaultComboBoxModel modelo31 = this.ModeloComboBox(31);
        DefaultComboBoxModel modelo30 = this.ModeloComboBox(30);
        DefaultComboBoxModel modelo28 = this.ModeloComboBox(28);
        DefaultComboBoxModel modelo29 = this.ModeloComboBox(29);
        i = jComboBox2.getSelectedIndex();
        switch (i) {
            case 0: {
                jComboBox1.setModel(modelo31);
                break;
            }
            case 1: {
                if ((Integer.parseInt(jComboBox3.getSelectedItem().toString())) % 4 == 0) {
                    jComboBox1.setModel(modelo29);
                    if (d >= 29) {
                        d = 28;
                    }
                } else {
                    jComboBox1.setModel(modelo28);
                    if (d >= 28) {
                        d = 27;
                    }
                }
                break;
            }
            case 2: {
                jComboBox1.setModel(modelo31);
                break;
            }
            case 3: {
                jComboBox1.setModel(modelo30);
                if (d >= 30) {
                    d = 29;
                }
                break;
            }
            case 4: {
                jComboBox1.setModel(modelo31);
                break;
            }
            case 5: {
                jComboBox1.setModel(modelo30);
                if (d >= 30) {
                    d = 29;
                }
                break;
            }
            case 6: {
                jComboBox1.setModel(modelo31);
                break;
            }
            case 7: {
                jComboBox1.setModel(modelo31);
                break;
            }
            case 8: {
                jComboBox1.setModel(modelo30);
                if (d >= 30) {
                    d = 29;
                }
                break;
            }
            case 9: {
                jComboBox1.setModel(modelo31);
                break;
            }
            case 10: {
                jComboBox1.setModel(modelo30);
                if (d >= 30) {
                    d = 29;
                }
                break;
            }
            case 11: {
                jComboBox1.setModel(modelo31);
                break;
            }

        }
        jComboBox1.setSelectedIndex(d);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reparación");

        jLabel1.setText("Tipo Reparacion");

        jLabel2.setText("Fecha");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jButton1.setText("Realizar reparación");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(48, 48, 48)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jButton1)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
    this.DarFormato();
}//GEN-LAST:event_jComboBox2ActionPerformed

private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
// TODO add your handling code here:
    DefaultComboBoxModel modelo28 = this.ModeloComboBox(28);
    DefaultComboBoxModel modelo29 = this.ModeloComboBox(29);
    int d = jComboBox1.getSelectedIndex();
    if (jComboBox2.getSelectedIndex() == 1) {
        if ((Integer.parseInt(jComboBox3.getSelectedItem().toString())) % 4 == 0) {
            jComboBox1.setModel(modelo29);
            if (d >= 29) {
                d = 28;
            }
        } else {
            jComboBox1.setModel(modelo28);
            if (d >= 28) {
                d = 27;
            }
        }
    }
    jComboBox1.setSelectedIndex(d);
}//GEN-LAST:event_jComboBox3ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    if (!jTextField1.getText().equalsIgnoreCase("")) {
        this.rep = new Reparacion(jTextField1.getText(), new GregorianCalendar(
                (Integer.parseInt(jComboBox3.getSelectedItem().toString())-1900),
                jComboBox2.getSelectedIndex(),
                (Integer.parseInt(jComboBox1.getSelectedItem().toString())+1)));
        this.cocheC.reparar(rep);
        this.setVisible(false);
    }
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReparacionIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReparacionIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReparacionIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReparacionIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ReparacionIG dialog = new ReparacionIG(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
