/****************************************
 * NOMBRE: Adrián Sanz Contreras        *
 * DNI: 49097240-Z                      *
 * Nº EXP: 145                          *
 *                                      *
 * NOMBRE: Alfonso Santamaría Rodríguez *
 * DNI: 49095131-K                      *   
 * Nº EXP: 63                           *
 *                                      *
 * NOMBRE: Fco Javier Pasamontes Moreno *
 * DNI: 47516684-H                      *
 * Nº EXP: 153                          *
 *                                      *
 * 2º GRADO EN INGERNIERÍA DEL SOFTWARE *
 * CURSO: 2011-2012                     *
 ****************************************/

/*
 * GestionDeClientesIG.java
 *
 * Created on 10-dic-2011, 13:06:24
 */
package practicaGrupal;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


public class GestionDeClientesIG extends javax.swing.JDialog {

    private ArrayList<Cliente> misClientes = new ArrayList<Cliente>();

    /** Creates new form GestionDeClientesIG */
    public GestionDeClientesIG(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbDarDeBaja = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtClientes = new javax.swing.JTable();
        jbDarDeAlta = new javax.swing.JButton();
        jbModificarDatos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de clientes");

        jbDarDeBaja.setText("Dar de baja");
        jbDarDeBaja.setEnabled(false);
        jbDarDeBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDarDeBajaActionPerformed(evt);
            }
        });

        jtClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtClientes);

        jbDarDeAlta.setText("Dar de alta");
        jbDarDeAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDarDeAltaActionPerformed(evt);
            }
        });

        jbModificarDatos.setText("Modificar datos");
        jbModificarDatos.setEnabled(false);
        jbModificarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbDarDeAlta)
                        .addGap(18, 18, 18)
                        .addComponent(jbDarDeBaja)
                        .addGap(38, 38, 38)
                        .addComponent(jbModificarDatos)
                        .addGap(93, 93, 93))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbDarDeBaja)
                    .addComponent(jbModificarDatos)
                    .addComponent(jbDarDeAlta))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbDarDeAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDarDeAltaActionPerformed
        AltaClienteIG altaClien = new AltaClienteIG(null, true);

        altaClien.setMisClientes(this.misClientes);

        altaClien.setLocationRelativeTo(null);
        altaClien.setVisible(true);

        this.misClientes = altaClien.getMisClientes();

        this.cargarClientes(this.misClientes);


    }//GEN-LAST:event_jbDarDeAltaActionPerformed

    private void jbDarDeBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDarDeBajaActionPerformed
        int i = 0;

        while ((!this.jtClientes.isRowSelected(i))
                && (i < this.jtClientes.getRowCount())) {
            i++;
        }

        if ((jtClientes.isRowSelected(i))
                && (this.misClientes.get(i).getCochesComprados().isEmpty())
                && (this.misClientes.get(i).getCochesReservados().isEmpty())) {
            this.misClientes.remove(i);
        }
        this.cargarClientes(this.misClientes);
    }//GEN-LAST:event_jbDarDeBajaActionPerformed

    private void jbModificarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarDatosActionPerformed
        int i = 0;

        //i representa el numero de la posición del empleado a modificar
        while ((!this.jtClientes.isRowSelected(i))
                && (i < this.jtClientes.getRowCount())) {
            i++;
        }

        //Con esta condición controlamos si se ha seleccionado alguna columna o no
        if (this.jtClientes.isRowSelected(i)) {
            //Creamos el nuevo JDialog 
            ModificarClienteIG modifClien = new ModificarClienteIG(null, true);

            //Al nuevo JDialog le enviamos los datos pertinentes
            modifClien.setMisClientes(this.misClientes);
            modifClien.setPos(i);


            //Cargamos los datos en los jTextField correspondientes de
            //ModificarExposicionIG
            modifClien.cargarDatosEnPaneles();
            modifClien.setLocationRelativeTo(null);
            modifClien.setVisible(true);

            this.misClientes = modifClien.getMisClientes();
            this.cargarClientes(this.misClientes);
        }
    }//GEN-LAST:event_jbModificarDatosActionPerformed

    private void jtClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtClientesMouseClicked
        // TODO add your handling code here:
        
        if (this.jtClientes.rowAtPoint(evt.getPoint()) >= 0 && this.jtClientes.isEnabled()){
            this.jbModificarDatos.setEnabled(true);
            this.jbDarDeBaja.setEnabled(true);
        }
    }//GEN-LAST:event_jtClientesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionDeClientesIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionDeClientesIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionDeClientesIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionDeClientesIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                GestionDeClientesIG dialog = new GestionDeClientesIG(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbDarDeAlta;
    private javax.swing.JButton jbDarDeBaja;
    private javax.swing.JButton jbModificarDatos;
    private javax.swing.JTable jtClientes;
    // End of variables declaration//GEN-END:variables

    public ArrayList<Cliente> getMisClientes() {
        return misClientes;
    }

    public void setMisClientes(ArrayList<Cliente> misClientes) {
        this.misClientes = misClientes;
    }

    public void cargarClientes(ArrayList<Cliente> listaClientes) {
        DefaultTableModel modelo = new DefaultTableModel();

        modelo.addColumn("Numero");
        modelo.addColumn("Dni");
        modelo.addColumn("Dirección");
        modelo.addColumn("Telefono");

        //Recorremos los proveedores
        Object[] fila = new Object[4];
        for (int i = 0; i < listaClientes.size(); i++) {
            fila[0] = listaClientes.get(i).getNombre();
            fila[1] = listaClientes.get(i).getDni();
            fila[2] = listaClientes.get(i).getDireccion();
            fila[3] = listaClientes.get(i).getTelefono();

            modelo.addRow(fila);
        }
        
        this.jbModificarDatos.setEnabled(false);
        this.jbDarDeBaja.setEnabled(false);

        jtClientes.setModel(modelo);
        this.misClientes = listaClientes;

    }
}
