/****************************************
 * NOMBRE: Adrián Sanz Contreras        *
 * DNI: 49097240-Z                      *
 * Nº EXP: 145                          *
 *                                      *
 * NOMBRE: Alfonso Santamaría Rodríguez *
 * DNI: 49095131-K                      *   
 * Nº EXP: 63                           *
 *                                      *
 * NOMBRE: Fco Javier Pasamontes Moreno *
 * DNI: 47516684-H                      *
 * Nº EXP: 153                          *
 *                                      *
 * 2º GRADO EN INGERNIERÍA DEL SOFTWARE *
 * CURSO: 2011-2012                     *
 ****************************************/
/*
 * GestionDeProveedoresIG.java
 *
 * Created on 10-dic-2011, 6:25:19
 */
package practicaGrupal;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class GestionDeProveedoresIG extends javax.swing.JDialog {

    private ArrayList<Proveedor> misProveedores = new ArrayList<Proveedor>();
    
    /** Creates new form GestionDeProveedoresIG */
    public GestionDeProveedoresIG(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbDarDeBaja = new javax.swing.JButton();
        jbModificarDatos = new javax.swing.JButton();
        jbDarDeAlta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProveedores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de proveedores");
        setResizable(false);

        jbDarDeBaja.setText("Dar de baja");
        jbDarDeBaja.setEnabled(false);
        jbDarDeBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDarDeBajaActionPerformed(evt);
            }
        });

        jbModificarDatos.setText("Modificar datos");
        jbModificarDatos.setEnabled(false);
        jbModificarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarDatosActionPerformed(evt);
            }
        });

        jbDarDeAlta.setText("Dar de alta");
        jbDarDeAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDarDeAltaActionPerformed(evt);
            }
        });

        jtProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtProveedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtProveedores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbDarDeAlta)
                        .addGap(37, 37, 37)
                        .addComponent(jbDarDeBaja)
                        .addGap(38, 38, 38)
                        .addComponent(jbModificarDatos)
                        .addGap(93, 93, 93))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbDarDeAlta)
                    .addComponent(jbDarDeBaja)
                    .addComponent(jbModificarDatos))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbDarDeAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDarDeAltaActionPerformed
        AltaProveedorIG altaProv = new AltaProveedorIG(null,true);
        
        altaProv.setMisProveedores(this.misProveedores);
        
        altaProv.setLocationRelativeTo(null);
        altaProv.setVisible(true);
   
        this.misProveedores = altaProv.getMisProveedores();
        
        this.cargarProveedores(this.misProveedores); 
        
    }//GEN-LAST:event_jbDarDeAltaActionPerformed

    private void jbDarDeBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDarDeBajaActionPerformed
        int i = 0;
        
        while ((!this.jtProveedores.isRowSelected(i)) &&
                (i < this.jtProveedores.getRowCount())) {
            i++;
        }
        if (jtProveedores.isRowSelected(i)) {
               this.misProveedores.remove(i);

            }
            this.cargarProveedores(this.misProveedores);
        
    }//GEN-LAST:event_jbDarDeBajaActionPerformed

    private void jbModificarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarDatosActionPerformed
        int i = 0;
        
        //i representa el numero de la posición del empleado a modificar
        while ((!this.jtProveedores.isRowSelected(i)) &&
                (i < this.jtProveedores.getRowCount())) {
            i++;
        }

        //Con esta condición controlamos si se ha seleccionado alguna columna o no

        //Creamos el nuevo JDialog 
        ModificarProveedorIG modifProv = new ModificarProveedorIG(null, true);

        //Al nuevo JDialog le enviamos los datos pertinentes
        modifProv.setMisProveedores(this.misProveedores);
        modifProv.setPos(i);
        

        //Cargamos los datos en los jTextField correspondientes de
        //ModificarEmpleadoIG
        modifProv.cargarDatosEnPaneles();
        modifProv.setLocationRelativeTo(null);
        modifProv.setVisible(true);
        
        this.misProveedores = modifProv.getMisProveedores();
        this.cargarProveedores(this.misProveedores);
    }//GEN-LAST:event_jbModificarDatosActionPerformed

    private void jtProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtProveedoresMouseClicked
        // TODO add your handling code here:
        if (this.jtProveedores.rowAtPoint(evt.getPoint()) >= 0 && this.jtProveedores.isEnabled()){
            this.jbModificarDatos.setEnabled(true);
            this.jbDarDeBaja.setEnabled(true);
        }
    }//GEN-LAST:event_jtProveedoresMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionDeProveedoresIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionDeProveedoresIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionDeProveedoresIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionDeProveedoresIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                GestionDeProveedoresIG dialog = new GestionDeProveedoresIG(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbDarDeAlta;
    private javax.swing.JButton jbDarDeBaja;
    private javax.swing.JButton jbModificarDatos;
    private javax.swing.JTable jtProveedores;
    // End of variables declaration//GEN-END:variables

    public ArrayList<Proveedor> getMisProveedores() {
        return misProveedores;
    }

    public void setMisProveedores(ArrayList<Proveedor> misProveedores) {
        this.misProveedores = misProveedores;
    }    
    
    public void cargarProveedores(ArrayList<Proveedor> listaProv) {
        DefaultTableModel modelo = new DefaultTableModel();

        modelo.addColumn("Nombre");
        modelo.addColumn("Dirección");
        modelo.addColumn("Código");
        modelo.addColumn("Tipo de coche");

        //Recorremos los empleados
        Object[] fila = new Object[4];
        for (int i = 0; i < this.misProveedores.size(); i++) {
            fila[0] = this.misProveedores.get(i).getNombre();
            fila[1] = this.misProveedores.get(i).getDireccion();
            fila[2] = this.misProveedores.get(i).getCodigo();
            fila[3] = this.misProveedores.get(i).getTipoCoche();
       
            modelo.addRow(fila);
        }      

        this.jbModificarDatos.setEnabled(false);
        this.jbDarDeBaja.setEnabled(false);
        jtProveedores.setModel(modelo);
        this.misProveedores = listaProv;

    }
}
