/****************************************
 * NOMBRE: Adrián Sanz Contreras        *
 * DNI: 49097240-Z                      *
 * Nº EXP: 145                          *
 *                                      *
 * NOMBRE: Alfonso Santamaría Rodríguez *
 * DNI: 49095131-K                      *   
 * Nº EXP: 63                           *
 *                                      *
 * NOMBRE: Fco Javier Pasamontes Moreno *
 * DNI: 47516684-H                      *
 * Nº EXP: 153                          *
 *                                      *
 * 2º GRADO EN INGERNIERÍA DEL SOFTWARE *
 * CURSO: 2011-2012                     *
 ****************************************/

/*
 * ModificarCocheProveedorIG.java
 *
 * Created on 13-dic-2011, 10:27:37
 */
package practicaGrupal;
import java.util.ArrayList;
import javax.swing.JOptionPane;


public class ModificarCocheProveedorIG extends javax.swing.JDialog {

    private ArrayList<Proveedor> misProveedores = new ArrayList<Proveedor>();
    private int proveedorSeleccionado;
    private int cocheSeleccionado;
    private boolean haModificadoCoche = false;
    
    /** Creates new form ModificarCocheProveedorIG */
    public ModificarCocheProveedorIG(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlModelo = new javax.swing.JLabel();
        jlMarca = new javax.swing.JLabel();
        jlMatricula = new javax.swing.JLabel();
        jlPrecioVenta = new javax.swing.JLabel();
        jtfPrecioVenta = new javax.swing.JTextField();
        jtfMatricula = new javax.swing.JTextField();
        jbModificar = new javax.swing.JButton();
        jtfMarca = new javax.swing.JTextField();
        jbVaciarDatos = new javax.swing.JButton();
        jtfModelo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar datos del coche de un proveedor");

        jlModelo.setText("Modelo");

        jlMarca.setText("Marca");

        jlMatricula.setText("Matrícula");

        jlPrecioVenta.setText("Precio de venta");

        jbModificar.setText("Modificar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jbVaciarDatos.setText("Vaciar datos");
        jbVaciarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVaciarDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jlMatricula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlPrecioVenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jtfMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(jtfPrecioVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(jtfModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(jtfMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jbModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jbVaciarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlMarca)
                    .addComponent(jtfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlModelo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPrecioVenta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlMatricula))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbModificar)
                    .addComponent(jbVaciarDatos))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbVaciarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVaciarDatosActionPerformed
       this.jtfMarca.setText("");
        this.jtfModelo.setText("");
        this.jtfPrecioVenta.setText("");
        this.jtfMatricula.setText("");
    }//GEN-LAST:event_jbVaciarDatosActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        if (!this.jtfMarca.getText().equalsIgnoreCase("")
                && !this.jtfModelo.getText().equalsIgnoreCase("")
                && !this.jtfPrecioVenta.getText().equalsIgnoreCase("")
                && !this.jtfMatricula.getText().equalsIgnoreCase("")) {
            if (JOptionPane.showConfirmDialog(this, "¿Desea modificar los datos?",
                    "Modificar datos del coche", JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION) {

                this.misProveedores.get(this.proveedorSeleccionado).
                        getCoches().set(this.cocheSeleccionado,
                        new Coche(this.jtfMarca.getText(), this.jtfModelo.getText(),
                        Double.parseDouble(this.jtfPrecioVenta.getText()),
                        this.jtfMatricula.getText(),
                        this.misProveedores.get(this.proveedorSeleccionado).
                        getCoches().get(this.cocheSeleccionado).
                        getTipoVehiculo()));
                JOptionPane.showMessageDialog(this,
                        "Datos del coche modificados");
                this.haModificadoCoche = true;
                this.setVisible(false);

            }
        }
        else{
           JOptionPane.showMessageDialog(this,
                        "Debe introducir algún dato para modificar los datos del coche"); 
        }
    }//GEN-LAST:event_jbModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarCocheProveedorIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarCocheProveedorIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarCocheProveedorIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarCocheProveedorIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                ModificarCocheProveedorIG dialog = new ModificarCocheProveedorIG(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbVaciarDatos;
    private javax.swing.JLabel jlMarca;
    private javax.swing.JLabel jlMatricula;
    private javax.swing.JLabel jlModelo;
    private javax.swing.JLabel jlPrecioVenta;
    private javax.swing.JTextField jtfMarca;
    private javax.swing.JTextField jtfMatricula;
    private javax.swing.JTextField jtfModelo;
    private javax.swing.JTextField jtfPrecioVenta;
    // End of variables declaration//GEN-END:variables

    public int getCocheSeleccionado() {
        return cocheSeleccionado;
    }

    public void setCocheSeleccionado(int cocheSeleccionado) {
        this.cocheSeleccionado = cocheSeleccionado;
    }

    public ArrayList<Proveedor> getMisProveedores() {
        return misProveedores;
    }

    public void setMisProveedores(ArrayList<Proveedor> misProveedores) {
        this.misProveedores = misProveedores;
    }

    public int getProveedorSeleccionado() {
        return proveedorSeleccionado;
    }

    public void setProveedorSeleccionado(int proveedorSeleccionado) {
        this.proveedorSeleccionado = proveedorSeleccionado;
    }

    public void cargarDatosCoche() {
        this.jtfMarca.setText(this.misProveedores.get(proveedorSeleccionado).
                getCoches().get(cocheSeleccionado).getMarca());
        this.jtfModelo.setText(this.misProveedores.get(proveedorSeleccionado).
                getCoches().get(cocheSeleccionado).getModelo());
        this.jtfPrecioVenta.setText(String.valueOf(this.misProveedores.
                get(proveedorSeleccionado).getCoches().get(cocheSeleccionado).
                getPrecioVenta()));
        this.jtfMatricula.setText(this.misProveedores.
                get(proveedorSeleccionado).getCoches().get(cocheSeleccionado).
                getMatricula());
    }

    public boolean isHaModificadoCoche() {
        return haModificadoCoche;
    }

    public void setHaModificadoCoche(boolean haModificadoCoche) {
        this.haModificadoCoche = haModificadoCoche;
    }
    
}

