/****************************************
 * NOMBRE: Adrián Sanz Contreras        *
 * DNI: 49097240-Z                      *
 * Nº EXP: 145                          *
 *                                      *
 * NOMBRE: Alfonso Santamaría Rodríguez *
 * DNI: 49095131-K                      *   
 * Nº EXP: 63                           *
 *                                      *
 * NOMBRE: Fco Javier Pasamontes Moreno *
 * DNI: 47516684-H                      *
 * Nº EXP: 153                          *
 *                                      *
 * 2º GRADO EN INGERNIERÍA DEL SOFTWARE *
 * CURSO: 2011-2012                     *
 ****************************************/

/*
 * ModificarEmpleadoIG.java
 *
 * Created on 10-dic-2011, 1:22:56
 */
package practicaGrupal;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class ModificarEmpleadoIG extends javax.swing.JDialog {

    private ArrayList<Empleado> listaEmp;
    private ArrayList<Comisionario> listaCom;
    private int pos;
    private String tipo;

    /** Creates new form ModificarEmpleadoIG */
    public ModificarEmpleadoIG(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbModificar = new javax.swing.JButton();
        jcbTipoEmpleado = new javax.swing.JComboBox();
        jlNombre = new javax.swing.JLabel();
        jlTipoEmpleado = new javax.swing.JLabel();
        jtfSalario = new javax.swing.JTextField();
        jlTelefono = new javax.swing.JLabel();
        jlDireccion = new javax.swing.JLabel();
        jlDni = new javax.swing.JLabel();
        jlSalario = new javax.swing.JLabel();
        jtfDireccion = new javax.swing.JTextField();
        jtfTelefono = new javax.swing.JTextField();
        jtfNombre = new javax.swing.JTextField();
        jtfDni = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar empleado");
        setResizable(false);

        jbModificar.setText("Modificar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jcbTipoEmpleado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vendedor", "Comisionario", "Director", "Mecanico" }));
        jcbTipoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTipoEmpleadoActionPerformed(evt);
            }
        });

        jlNombre.setText("Nombre");

        jlTipoEmpleado.setText("Tipo de empleado");

        jlTelefono.setText("Telefono");

        jlDireccion.setText("Direccion");

        jlDni.setText("DNI");

        jlSalario.setText("Salario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlTipoEmpleado)
                                .addGap(37, 37, 37)
                                .addComponent(jcbTipoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jlSalario)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jlTelefono)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jlDireccion)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jlDni)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfDni, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jlNombre)
                                    .addGap(51, 51, 51)
                                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jbModificar)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombre)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDni)
                    .addComponent(jtfDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDireccion)
                    .addComponent(jtfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTelefono)
                    .addComponent(jtfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSalario)
                    .addComponent(jtfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTipoEmpleado)
                    .addComponent(jcbTipoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbModificar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbTipoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTipoEmpleadoActionPerformed
        this.jtfSalario.setVisible(!this.jcbTipoEmpleado.getSelectedItem().toString().equalsIgnoreCase("Comisionario"));         this.jlSalario.setVisible(!this.jcbTipoEmpleado.getSelectedItem().toString().equalsIgnoreCase("Comisionario"));     }//GEN-LAST:event_jcbTipoEmpleadoActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
       //Creamos un nuevo objeto de la clase empleado o de la clase comisionario
       //y lo introducimos en la misma posicion en la que estaba, previo borrado
       //del objeto sin modificar
       
       if (this.jcbTipoEmpleado.getSelectedItem().toString().equalsIgnoreCase("Comisionario")) {
            try {
                this.listaCom.add(this.listaCom.size(), new Comisionario(this.jtfNombre.getText(),
                        this.jtfDni.getText(),
                        this.jtfDireccion.getText(),
                        Long.parseLong(this.jtfTelefono.getText())));
                if (this.tipo.equalsIgnoreCase("Comisionario")) {
                    this.listaCom.remove(this.pos);
                } else {
                    this.listaEmp.remove(this.pos);
                }

                this.setVisible(false);
            } catch (Exception ex) {
                String problema = new String();

                if (this.jtfNombre.getText().equalsIgnoreCase("")) {
                    problema = problema + "Debe introducir un nombre.\n";
                }
                if (this.jtfDni.getText().equalsIgnoreCase("")) {
                    problema = problema + "Debe introducir un dni.\n";
                }
                if (this.jtfDireccion.getText().equalsIgnoreCase("")) {
                    problema = problema + "Debe introducir una dirección.\n";
                }
                if (this.jtfTelefono.getText().equalsIgnoreCase("")) {
                    problema = problema + "Debe introducir un teléfono.\n";
                }
                JOptionPane.showConfirmDialog(this, problema, "Error",
                        JOptionPane.PLAIN_MESSAGE, JOptionPane.ERROR_MESSAGE);
            }

        } else {
            try {
                this.listaEmp.add(this.listaEmp.size(), new Empleado(this.jtfNombre.getText(),
                        this.jtfDni.getText(),
                        this.jtfDireccion.getText(),
                        Long.parseLong(this.jtfTelefono.getText()),
                        Double.parseDouble(this.jtfSalario.getText()),
                        this.jcbTipoEmpleado.getSelectedItem().toString()));
                if (this.tipo.equalsIgnoreCase("Comisionario")) {
                    this.listaCom.remove(this.pos);
                } else {
                    this.listaEmp.remove(this.pos);
                }
                this.setVisible(false);
            } catch (Exception ex) {
                String problema = new String();

                if (this.jtfNombre.getText().equalsIgnoreCase("")) {
                    problema = problema + "Debe introducir un nombre.\n";
                }
                if (this.jtfDni.getText().equalsIgnoreCase("")) {
                    problema = problema + "Debe introducir un dni.\n";
                }
                if (this.jtfDireccion.getText().equalsIgnoreCase("")) {
                    problema = problema + "Debe introducir una dirección.\n";
                }
                if (this.jtfTelefono.getText().equalsIgnoreCase("")) {
                    problema = problema + "Debe introducir un teléfono.\n";
                }
                if (this.jtfSalario.getText().equalsIgnoreCase("")) {
                    problema = problema + "Debe introducir un salario.\n";
                }
                JOptionPane.showConfirmDialog(this, problema, "Error",
                        JOptionPane.PLAIN_MESSAGE, JOptionPane.ERROR_MESSAGE);
            }
        } 
    }//GEN-LAST:event_jbModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarEmpleadoIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarEmpleadoIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarEmpleadoIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarEmpleadoIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                ModificarEmpleadoIG dialog = new ModificarEmpleadoIG(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbModificar;
    private javax.swing.JComboBox jcbTipoEmpleado;
    private javax.swing.JLabel jlDireccion;
    private javax.swing.JLabel jlDni;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlSalario;
    private javax.swing.JLabel jlTelefono;
    private javax.swing.JLabel jlTipoEmpleado;
    private javax.swing.JTextField jtfDireccion;
    private javax.swing.JTextField jtfDni;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfSalario;
    private javax.swing.JTextField jtfTelefono;
    // End of variables declaration//GEN-END:variables
    
    public ArrayList getListaCom() {
        return listaCom;
    }

    public void setListaCom(ArrayList<Comisionario> listaCom) {
        this.listaCom = listaCom;
    }

    public ArrayList getListaEmp() {
        return listaEmp;
    }

    public void setListaEmp(ArrayList<Empleado> listaEmp) {
        this.listaEmp = listaEmp;
    }

    public int getPos() {
        return pos;
    }

    public void setPos(int pos) {
        this.pos = pos;
    }

    public String getTipo() {
        return tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    
    public void cargarDatosEnPaneles(){
        if (this.tipo.equalsIgnoreCase("Comisionario")){
            this.jtfNombre.setText(this.listaCom.get(this.pos).getNombre());
            this.jtfDni.setText(this.listaCom.get(this.pos).getDni());
            this.jtfDireccion.setText(this.listaCom.get(this.pos).getDireccion());
            this.jtfTelefono.setText(Long.toString(this.listaCom.get(this.pos).getTelefono()));
            this.jcbTipoEmpleado.setSelectedItem("Comisionario");
        }
        else{
            this.jtfNombre.setText(this.listaEmp.get(this.pos).getNombre());
            this.jtfDni.setText(this.listaEmp.get(this.pos).getDni());
            this.jtfDireccion.setText(this.listaEmp.get(this.pos).getDireccion());
            this.jtfTelefono.setText(Long.toString(this.listaEmp.get(this.pos).getTelefono()));
            this.jtfSalario.setText(Double.toString(this.listaEmp.get(this.pos).getSalario()));
            this.jcbTipoEmpleado.setSelectedItem(this.listaEmp.get(this.pos).getTipoEmpleado());
        }
    }
}
