/****************************************
 * NOMBRE: Adrián Sanz Contreras        *
 * DNI: 49097240-Z                      *
 * Nº EXP: 145                          *
 *                                      *
 * NOMBRE: Alfonso Santamaría Rodríguez *
 * DNI: 49095131-K                      *   
 * Nº EXP: 63                           *
 *                                      *
 * NOMBRE: Fco Javier Pasamontes Moreno *
 * DNI: 47516684-H                      *
 * Nº EXP: 153                          *
 *                                      *
 * 2º GRADO EN INGERNIERÍA DEL SOFTWARE *
 * CURSO: 2011-2012                     *
 ****************************************/

/*
 * ModificarCocheConcesionarioIG.java
 *
 * Created on 13-dic-2011, 15:53:42
 */
package practicaGrupal;
import java.util.ArrayList;
import javax.swing.JOptionPane;


public class ModificarCocheConcesionarioIG extends javax.swing.JDialog {
    private ArrayList<CocheConcesionario> misCochesC = 
            new ArrayList<CocheConcesionario>();
    private int rowCocheSeleccionado;

    /** Creates new form ModificarCocheConcesionarioIG */
    public ModificarCocheConcesionarioIG(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlMarca = new javax.swing.JLabel();
        jlModelo = new javax.swing.JLabel();
        jbVaciarDatos = new javax.swing.JButton();
        jtfMatricula = new javax.swing.JTextField();
        jtfPrecioVentaPublico = new javax.swing.JTextField();
        jlPrecioVentaPublico = new javax.swing.JLabel();
        jlMatricula = new javax.swing.JLabel();
        jtfMarca = new javax.swing.JTextField();
        jbModificar = new javax.swing.JButton();
        jtfModelo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar los datos de un coche del concesionario");

        jlMarca.setText("Marca");

        jlModelo.setText("Modelo");

        jbVaciarDatos.setText("Vaciar datos");
        jbVaciarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVaciarDatosActionPerformed(evt);
            }
        });

        jlPrecioVentaPublico.setText("Precio de compra");

        jlMatricula.setText("Matrícula");

        jbModificar.setText("Modificar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlMatricula)
                    .addComponent(jlPrecioVentaPublico, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jtfMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(jtfPrecioVentaPublico, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(jtfModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(jtfMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jbModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jbVaciarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlMarca)
                    .addComponent(jtfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlModelo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPrecioVentaPublico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPrecioVentaPublico))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlMatricula))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbModificar)
                    .addComponent(jbVaciarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        if (!this.jtfMarca.getText().equalsIgnoreCase("")
                && !this.jtfModelo.getText().equalsIgnoreCase("")
                && !this.jtfPrecioVentaPublico.getText().equalsIgnoreCase("")
                && !this.jtfMatricula.getText().equalsIgnoreCase("")) {
            if (JOptionPane.showConfirmDialog(this, "¿Desea modificar los datos?",
                    "Modificar datos del coche", JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION) {

                
                this.misCochesC.set(this.rowCocheSeleccionado,
                        
                
                new CocheConcesionario(this.jtfMarca.getText(), 
                        this.jtfModelo.getText(),
                        this.misCochesC.get(this.rowCocheSeleccionado).
                        getPrecioVenta(),this.jtfMatricula.getText(),
                        this.misCochesC.get(this.rowCocheSeleccionado).
                        getTipoVehiculo(),Float.parseFloat(this.
                        jtfPrecioVentaPublico.getText()),
                        this.misCochesC.get(this.rowCocheSeleccionado).
                        getEstado()));
                       
                JOptionPane.showMessageDialog(this,"Datos del coche modificados");
//                this.haModificadoCoche = true;
                this.setVisible(false);

            }
        }
        else{
           JOptionPane.showMessageDialog(this,
                        "Debe introducir algún dato para modificar los datos del coche"); 
        }
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jbVaciarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVaciarDatosActionPerformed
        this.jtfMarca.setText("");
        this.jtfModelo.setText("");
        this.jtfPrecioVentaPublico.setText("");
        this.jtfMatricula.setText("");
    }//GEN-LAST:event_jbVaciarDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarCocheConcesionarioIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarCocheConcesionarioIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarCocheConcesionarioIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarCocheConcesionarioIG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ModificarCocheConcesionarioIG dialog = new ModificarCocheConcesionarioIG(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbVaciarDatos;
    private javax.swing.JLabel jlMarca;
    private javax.swing.JLabel jlMatricula;
    private javax.swing.JLabel jlModelo;
    private javax.swing.JLabel jlPrecioVentaPublico;
    private javax.swing.JTextField jtfMarca;
    private javax.swing.JTextField jtfMatricula;
    private javax.swing.JTextField jtfModelo;
    private javax.swing.JTextField jtfPrecioVentaPublico;
    // End of variables declaration//GEN-END:variables

    public ArrayList<CocheConcesionario> getMisCochesC() {
        return misCochesC;
    }

    public void setMisCochesC(ArrayList<CocheConcesionario> misCochesC) {
        this.misCochesC = misCochesC;
    }

    public int getRowCocheSeleccionado() {
        return rowCocheSeleccionado;
    }

    public void setRowCocheSeleccionado(int rowCocheSeleccionado) {
        this.rowCocheSeleccionado = rowCocheSeleccionado;
    }

    public void cargarDatos(){
       this.jtfMarca.setText(this.misCochesC.get(this.rowCocheSeleccionado).
               getMarca());
        this.jtfModelo.setText(this.misCochesC.get(this.rowCocheSeleccionado).
                getModelo());
        this.jtfPrecioVentaPublico.setText(String.valueOf(this.misCochesC.
                get(this.rowCocheSeleccionado).getPrecioCompra()));
        this.jtfMatricula.setText(this.misCochesC.get(this.rowCocheSeleccionado)
                .getMatricula());
    }
}
